### ISSUE TITLE
Allow parameters for rust migrations

### ISSUE THREAD

**Issue by eiswind** [tamasfe/sqlx-migrate#1]
I stumbled upon your project today, and I wonder what you think about the idea to be able to pass some parameters into the rust based migrations.

The background of my idea is, that this would allow me to run the migrations on different schemas as needed (I am working on a multi-tenant application, and this would allow me to have a separate schema for each tenant).

I am quite a newbie when it comes to rust, but if you are interested, I would try to implement this and create a PR.

**Comment by tamasfe** [comment]
I would usually avoid altering migrations, but in some cases this could be definitely a useful feature!

> I am quite a newbie when it comes to rust, but if you are interested, I would try to implement this and create a PR.

Sure, it's very much welcome if you're interested and have the time. Instead of adding parameters directly to the migration functions, I would wrap and replace the transaction parameter (`&mut Transaction<'_ Postgres>`) with a context that we could add features to. This context could be generic over an additional configuration type as well that would default to if not specified `()`, e.g. `TransactionContext<Posgres, FooConfig>`. Let me know what you think.

**Comment by eiswind** [comment]
Unfortunately I don't find time to try this atm. I'll get back to it if it gets better
